---
# Development environment inventory
all:
  children:
    web_servers:
      hosts:
        web01.dev.example.com:
          ansible_host: 10.0.1.10
          ansible_user: ubuntu
        web02.dev.example.com:
          ansible_host: 10.0.1.11
          ansible_user: ubuntu
      vars:
        # Group-level variables for web servers
        datadog_role_tags:
          - "role:web"
          - "service:nginx"
    
    database_servers:
      hosts:
        db01.dev.example.com:
          ansible_host: 10.0.2.10
          ansible_user: ubuntu
        db02.dev.example.com:
          ansible_host: 10.0.2.11
          ansible_user: ubuntu
      vars:
        # Group-level variables for database servers
        datadog_role_tags:
          - "role:database"
          - "service:postgresql"
    
    application_servers:
      hosts:
        app01.dev.example.com:
          ansible_host: 10.0.3.10
          ansible_user: ubuntu
        app02.dev.example.com:
          ansible_host: 10.0.3.11
          ansible_user: ubuntu
      vars:
        # Group-level variables for application servers
        datadog_role_tags:
          - "role:app"
          - "service:java"
    
    # Environment-specific group
    dev_environment:
      children:
        - web_servers
        - database_servers
        - application_servers
      vars:
        # Environment-level variables
        datadog_env_tags:
          - "env:dev"
          - "tier:development"
