---
# Staging environment inventory
all:
  children:
    staging_servers:
      hosts:
        staging-web-01:
          ansible_host: 192.168.2.10
          datadog_host_tags:
            - "role:web"
            - "service:nginx"
        staging-web-02:
          ansible_host: 192.168.2.11
          datadog_host_tags:
            - "role:web"
            - "service:nginx"
        staging-db-01:
          ansible_host: 192.168.2.20
          datadog_host_tags:
            - "role:database"
            - "service:postgresql"
        staging-app-01:
          ansible_host: 192.168.2.30
          datadog_host_tags:
            - "role:application"
            - "service:nodejs"
        staging-app-02:
          ansible_host: 192.168.2.31
          datadog_host_tags:
            - "role:application"
            - "service:nodejs"
      vars:
        # Staging specific variables
        datadog_log_level: WARN
        webhook_notifications_enabled: true
        batch_size: "25%"
        max_fail_percentage: 15
