---
# Production environment inventory
all:
  children:
    prod_servers:
      hosts:
        prod-web-01:
          ansible_host: 10.0.1.10
          datadog_host_tags:
            - "role:web"
            - "service:nginx"
            - "critical:true"
        prod-web-02:
          ansible_host: 10.0.1.11
          datadog_host_tags:
            - "role:web"
            - "service:nginx"
            - "critical:true"
        prod-web-03:
          ansible_host: 10.0.1.12
          datadog_host_tags:
            - "role:web"
            - "service:nginx"
            - "critical:true"
        prod-db-01:
          ansible_host: 10.0.1.20
          datadog_host_tags:
            - "role:database"
            - "service:postgresql"
            - "critical:true"
        prod-db-02:
          ansible_host: 10.0.1.21
          datadog_host_tags:
            - "role:database"
            - "service:postgresql"
            - "critical:true"
        prod-app-01:
          ansible_host: 10.0.1.30
          datadog_host_tags:
            - "role:application"
            - "service:nodejs"
            - "critical:true"
        prod-app-02:
          ansible_host: 10.0.1.31
          datadog_host_tags:
            - "role:application"
            - "service:nodejs"
            - "critical:true"
        prod-app-03:
          ansible_host: 10.0.1.32
          datadog_host_tags:
            - "role:application"
            - "service:nodejs"
            - "critical:true"
      vars:
        # Production specific variables
        datadog_log_level: ERROR
        webhook_notifications_enabled: true
        batch_size: "10%"
        max_fail_percentage: 5
