---
# Development environment inventory
all:
  children:
    dev_servers:
      hosts:
        dev-web-01:
          ansible_host: 192.168.1.10
          datadog_host_tags:
            - "role:web"
            - "service:nginx"
        dev-web-02:
          ansible_host: 192.168.1.11
          datadog_host_tags:
            - "role:web"
            - "service:nginx"
        dev-db-01:
          ansible_host: 192.168.1.20
          datadog_host_tags:
            - "role:database"
            - "service:postgresql"
        dev-app-01:
          ansible_host: 192.168.1.30
          datadog_host_tags:
            - "role:application"
            - "service:nodejs"
        dev-app-02:
          ansible_host: 192.168.1.31
          datadog_host_tags:
            - "role:application"
            - "service:nodejs"
      vars:
        # Development specific variables
        datadog_log_level: INFO
        webhook_notifications_enabled: false
        batch_size: "50%"
        max_fail_percentage: 20
